name: Test CI Pipeline

on:
  push:
    branches: ["**"]

jobs:
  hello-word-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Affichage message Hello world
        run: echo "Hello World FROM CI"
